include:
  - docker-compose-db.yml
services:
  learning-service:
    container_name: demodb_application
    depends_on:
      db:
        condition: service_started
    build:
      dockerfile: Dockerfile
    image: demodb_application:latest
    environment:
      - DB_HOST=mysql_learning
      - DB_NAME=learning_db
      - DB_USERNAME=learning
      - DB_PASSWORD=learning
      - DB_PORT=3306
    ports:
      - "8080:8080"
    expose:
      - "8080"
    volumes:
      - ./.infra/logs/:/logs/